name: dasher
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_rust_bridge: ^1.49.0
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  platform: ^3.1.0
  ffi: ^2.0.1
  web_ffi: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  ffigen: ^6.1.2

flutter:
  uses-material-design: true
