name: flutter_rust_bridge
description: High-level memory-safe binding generator for Flutter/Dart <-> Rust
version: 1.49.0
repository: https://github.com/fzyzcjy/flutter_rust_bridge
environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  args: ^2.3.1
  build_cli_annotations: ^2.1.0
  colorize: ^3.0.0
  js: ^0.6.4
  meta: ^1.3.0
  # required by integration_test
  path: ^1.8.1
  puppeteer: ^2.12.0
  shelf: ^1.3.2
  shelf_static: ^1.1.1
  shelf_web_socket: ^1.0.2
  uuid: ^3.0.6
  web_socket_channel: ^2.2.0
  yaml: ^3.1.1
dev_dependencies:
  build_cli: ^2.2.0
  build_runner: ^2.2.0
  lints: ">=1.0.1 <3.0.0"
  test: ^1.16.8
executables:
  flutter_rust_bridge_serve: serve
